# Create an Alpine Image with node installed
FROM node:alpine

# Change to app dir inside image
WORKDIR /app

# Copy the package.json in the workdir
COPY package.json .

# Install all dependencies
RUN npm install

# Copy the rest of the files
COPY . .

# Execute npm start
CMD ["npm", "start"]
