apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests: # shouldn't add the persistent Volumes and dbs to skaffold
      - ./infra/k8s/nats-depl.yaml
      - ./infra/k8s/client/*
      - ./infra/k8s/menu/menu-depl.yaml
      - ./infra/k8s/notification/notification-depl.yaml
      - ./infra/k8s/order/order-depl.yaml
      - ./infra/k8s/restaurant/restaurant-depl.yaml
      - ./infra/k8s/user/user-depl.yaml
      - ./infra/k8s-dev/*
build:
  local:
    push: false
  artifacts:
    - image: isengart/food-user
      context: user
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: isengart/food-restaurant
      context: restaurant
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: isengart/food-menu
      context: menu
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: isengart/food-order
      context: order
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: isengart/food-notification
      context: notification
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: isengart/food-client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.js'
            dest: .
    - image: isengart/food-client-restaurant
      context: client-restaurant
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.js'
            dest: .
