apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests: # shouldn't add the persistent Volumes and dbs to skaffold
      - ./infra/k8s/nats-depl.yaml
      - ./infra/k8s/client/client-depl.yaml
      - ./infra/k8s/client/client-restaurant-depl.yaml
      - ./infra/k8s/menu/menu-depl.yaml
      - ./infra/k8s/notification/notification-depl.yaml
      - ./infra/k8s/order/order-depl.yaml
      - ./infra/k8s/restaurant/restaurant-depl.yaml
      - ./infra/k8s/user/user-depl.yaml
      - ./infra/k8s/query/query-depl.yaml
      - ./infra/k8s/payment/payment-depl.yaml
      - ./infra/k8s/expiration/expiration-redis-depl.yaml
      - ./infra/k8s/expiration/expiration-depl.yaml
      - ./infra/k8s-dev/*
      - ./infra/k8s/database-pvc.yaml #added it to refresh schemas
      - ./infra/k8s/menu/menu-mongo-depl.yaml #added it to refresh schemas
      - ./infra/k8s/restaurant/restaurant-mongo-depl.yaml #added it to refresh schemas
      - ./infra/k8s/order/order-mongo-depl.yaml #added it to refresh schemas
      - ./infra/k8s/user/user-mongo-depl.yaml #added it to refresh schemas
      - ./infra/k8s/query/query-mongo-depl.yaml #added it to refresh schemas
      - ./infra/k8s/payment/payment-mongo-depl.yaml #added it to refresh schemas
build:
  local:
    push: false
  artifacts:
    - image: isengart/food-user
      context: user
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: isengart/food-restaurant
      context: restaurant
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: isengart/food-menu
      context: menu
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: isengart/food-order
      context: order
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: isengart/food-payment
      context: payment
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: isengart/food-notification
      context: notification
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: isengart/food-query
      context: query
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: isengart/food-expiration
      context: expiration
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: isengart/food-client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        infer:
          - '**/*.ts'
          - '**/*.tsx'
          - '**/*.less'
    - image: isengart/food-client-restaurant
      context: client-restaurant
      docker:
        dockerfile: Dockerfile
      sync:
        infer:
          - '**/*.ts'
          - '**/*.tsx'
          - '**/*.less'
