apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-mongo-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restaurant-mongo
  template:
    metadata:
      labels:
        app: restaurant-mongo
    spec:
#      volumes: # Adding a PVC
#        - name: restaurant-mongo-storage
#          persistentVolumeClaim:
#            claimName: database-persistent-volume-claim
      containers:
        - name: restaurant-mongo
          image: mongo
#          volumeMounts:
#            - name: restaurant-mongo-storage
#              mountPath: /data/db
---
apiVersion: v1
kind: Service
metadata:
  name: restaurant-mongo-srv
spec:
  selector:
    app: restaurant-mongo
  ports:
    - name: db
      protocol: TCP
      port: 27017
      targetPort: 27017
