apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-restaurant-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-restaurant
  template:
    metadata:
      labels:
        app: client-restaurant
    spec:
      containers:
        - name: client-restaurant
          image: isengart/food-client-restaurant #docker image
---
apiVersion: v1
kind: Service
metadata:
  name: client-restaurant-srv
spec:
  selector:
    app: client-restaurant
  ports:
    - name: client-restaurant
      protocol: TCP
      port: 3000
      targetPort: 3000
