export enum UserTypes {
  GET_CURRENT_USER_START = 'user/get_current_user',
  GET_CURRENT_USER_SUCCESS = 'user/get_current_user_success',
  GET_CURRENT_USER_ERROR = 'user/get_current_user_error',
  SIGN_IN_USER_START = 'user/sign_in_user_start',
  SIGN_IN_USER_SUCCESS = 'user/sign_in_user_success',
  SIGN_IN_USER_ERROR = 'user/sign_in_user_error',
  SIGN_OUT_USER_START = 'user/sing_out_user_start',
  SIGN_OUT_USER_SUCCESS = 'user/sign_out_user_success',
  SIGN_OUT_USER_ERROR = 'user/sign_out_user_error',
  REGISTER_USER_START = 'user/register_user_start',
  REGISTER_USER_SUCCESS = 'user/register_user_success',
  REGISTER_USER_ERROR = 'user/register_user_error',
  CLEAR_USER_ERRORS = 'user/clear_user_errors',
  GET_CURRENT_USER_ADDRESSES_START = 'user/get_current_user_addresses_start',
  GET_CURRENT_USER_ADDRESSES_SUCCESS = 'user/get_current_user_addresses_success',
  GET_CURRENT_USER_ADDRESSES_ERROR = 'user/get_current_user_addresses_error',
  ADD_USER_ADDRESS_START = 'user/add_user_address_start',
  ADD_USER_ADDRESS_SUCCESS = 'user/add_user_address_success',
  ADD_USER_ADDRESS_ERROR = 'user/add_user_address_error',
  SELECT_USER_ADDRESS = 'user/select_user_address',
}
