export const GET_CURRENT_USER_START = 'user/GET_CURRENT_USER_START';
export const GET_CURRENT_USER_SUCCESS = 'user/GET_CURRENT_USER_SUCCESS';
export const GET_CURRENT_USER_ERROR = 'user/GET_CURRENT_USER_ERROR';

export const USER_LOGIN_START = 'user/USER_LOGIN_START';
export const SUCCESS_LOGIN = 'user/SUCCESS_LOGIN';
export const USER_LOGIN_ERROR ='user/USER_LOGIN_ERROR';

export const LOG_OUT_USER = 'user/LOGOUT_USER';


export const REGISTER_USER_START = 'user/REGISTER_USER_START';
export const REGISTER_USER_ERROR = 'user/REGISTER_USER_ERROR';
export const REGISTER_USER_SUCCESS = 'user/REGISTER_USER_SUCCESS';
